export default {
  ERR_ACCOUNT_NOT_FOUND: "用户未找到",
  ERR_PWD_NOT_CORRECT: "密码不正确",
  ERR_OLD_PWD_NOT_CORRECT: "旧密码不正确",
  ERR_TWO_PWD_NOT_CORRECT: "两次密码不相同",
  ERR_USER_NOT_LOGIN: "用户未登录",
  ERR_USER_NOT_FOUND: "用户已注销",
  ERR_ACCOUNT_EXIST: "用户已存在",
  ERR_FORM_DATA: "表单数据格式错误",
  ERR_PROBLEM_DATA: "问题格式错误",
  ERR_FORM_ENDED: "表单已结束",
  ERR_FORM_NOT_FOUND: "表单未找到",
  ERR_FORM_RESULT_NOT_FOUND: "表单结果未找到",
  ERR_FORM_RESULT: "表单结果错误",
  ERR_FORM_NOT_START: "表单未开始",
  ERR_PARAMS_LOST: "参数缺失",
  ERR_STAR_NOT_FOUND: "收藏的问题未找到",
  ERR_TYPE_NOT_FOUND: "类型未找到",
  ERR_PARAMS_TYPE_NOT_CORRECT: "参数类型不正确",
};
